from __future__ import annotations

from dataclasses import dataclass
import math
import random
from typing import Any

import torch
from torch.utils.data import Dataset

from wpu.core.state import Event, Relation, WorldObject, WorldState
from wpu.data.object_physics import BRANCH_LABELS
from wpu.data.working_set_physics import _indexed_object_ids, _project_state
from wpu.models.batch import OBJECT_FEATURE_DIM, StateGraphBatch


@dataclass(slots=True)
class PyBulletCupSample:
    state: WorldState
    event: Event
    target_object_delta: torch.Tensor
    branch_label: int
    causal_working_set_size: int
    simulator_metadata: dict[str, Any]


class PyBulletCupDataset(Dataset):
    """Object-state benchmark generated by a PyBullet rigid-body rollout.

    The dataset deliberately exposes simulator object states, not rendered
    pixels. That isolates WPU's state-processing claim from the separate
    perception-to-objectification problem.
    """

    def __init__(
        self,
        size: int = 128,
        seed: int = 31,
        background_objects: int = 8,
        steps: int = 240,
        time_step: float = 1.0 / 120.0,
        catch_probability: float = 0.45,
        balanced_labels: bool = False,
    ) -> None:
        self.size = size
        self.seed = seed
        self.background_objects = background_objects
        self.steps = steps
        self.time_step = time_step
        self.catch_probability = catch_probability
        self.balanced_labels = balanced_labels
        try:
            import pybullet as pybullet
        except ImportError as error:  # pragma: no cover - exercised when optional dep is absent.
            raise RuntimeError(
                "PyBulletCupDataset requires the optional 'pybullet' dependency. "
                "Install it with `pip install pybullet` or `pip install .[sim]`."
            ) from error
        self._p = pybullet
        self._client = self._p.connect(self._p.DIRECT)

    def __del__(self) -> None:
        client = getattr(self, "_client", None)
        p = getattr(self, "_p", None)
        if p is not None and client is not None:
            try:
                p.disconnect(client)
            except Exception:
                pass

    def __len__(self) -> int:
        return self.size

    def __getitem__(self, index: int) -> PyBulletCupSample:
        if self.balanced_labels:
            target_label = index % len(BRANCH_LABELS)
            for attempt in range(512):
                sample = self._make_sample(index * 1009 + attempt)
                if sample.branch_label == target_label:
                    return sample
        return self._make_sample(index)

    def _make_sample(self, index: int) -> PyBulletCupSample:
        rng = random.Random(self.seed + index)
        cup_x = rng.uniform(0.62, 0.96)
        hand_x = rng.uniform(0.18, 0.58)
        force = rng.uniform(0.2, 1.8)
        catch_action = rng.random() < self.catch_probability
        lateral_noise = rng.uniform(-0.08, 0.08)

        self._reset_world()
        body_ids = self._build_scene(
            cup_x=cup_x,
            hand_x=hand_x,
            catch_action=catch_action,
            rng=rng,
        )
        initial = self._read_body_states(body_ids)
        self._p.resetBaseVelocity(
            body_ids["cup_001"],
            linearVelocity=[force * 1.9, lateral_noise, 0.05 * force],
            angularVelocity=[0.0, force * 1.2, lateral_noise],
            physicsClientId=self._client,
        )
        for _ in range(self.steps):
            self._p.stepSimulation(physicsClientId=self._client)
        final = self._read_body_states(body_ids)

        label = _branch_label(
            final["cup_001"],
            initial_x=initial["cup_001"]["position"][0],
            catch_action=catch_action,
            edge_x=1.0,
        )
        state = _world_state_from_simulation(
            initial,
            cup_x=cup_x,
            hand_x=hand_x,
            force=force,
            catch_action=catch_action,
            background_objects=self.background_objects,
        )
        event = Event(
            type="simulated_hand_impulse",
            target="cup_001",
            delta={"position": [force * 0.08, lateral_noise, 0.0], "force": force, "catch_action": float(catch_action)},
            confidence=0.98,
            time=self.time_step,
            metadata={"simulator": "pybullet", "steps": self.steps},
        )
        target = _target_delta_tensor(state, initial, final)
        causal_k = 5 if catch_action else 4
        return PyBulletCupSample(
            state=state,
            event=event,
            target_object_delta=target,
            branch_label=label,
            causal_working_set_size=causal_k,
            simulator_metadata={
                "cup_x": cup_x,
                "hand_x": hand_x,
                "force": force,
                "catch_action": catch_action,
                "label": BRANCH_LABELS[label],
            },
        )

    def _reset_world(self) -> None:
        p = self._p
        p.resetSimulation(physicsClientId=self._client)
        p.setGravity(0.0, 0.0, -9.81, physicsClientId=self._client)
        p.setTimeStep(self.time_step, physicsClientId=self._client)
        p.setPhysicsEngineParameter(numSolverIterations=80, physicsClientId=self._client)

    def _build_scene(
        self,
        *,
        cup_x: float,
        hand_x: float,
        catch_action: bool,
        rng: random.Random,
    ) -> dict[str, int]:
        p = self._p
        table_collision = p.createCollisionShape(p.GEOM_BOX, halfExtents=[0.5, 0.35, 0.04], physicsClientId=self._client)
        table_id = p.createMultiBody(baseMass=0.0, baseCollisionShapeIndex=table_collision, basePosition=[0.5, 0.0, 0.36], physicsClientId=self._client)
        cup_collision = p.createCollisionShape(p.GEOM_BOX, halfExtents=[0.045, 0.045, 0.075], physicsClientId=self._client)
        cup_id = p.createMultiBody(baseMass=0.18, baseCollisionShapeIndex=cup_collision, basePosition=[cup_x, 0.0, 0.485], physicsClientId=self._client)
        p.changeDynamics(cup_id, -1, lateralFriction=0.38, rollingFriction=0.02, spinningFriction=0.02, physicsClientId=self._client)

        hand_collision = p.createCollisionShape(p.GEOM_SPHERE, radius=0.045, physicsClientId=self._client)
        hand_id = p.createMultiBody(baseMass=0.0, baseCollisionShapeIndex=hand_collision, basePosition=[hand_x, -0.16, 0.50], physicsClientId=self._client)

        edge_collision = p.createCollisionShape(p.GEOM_BOX, halfExtents=[0.01, 0.36, 0.02], physicsClientId=self._client)
        edge_id = p.createMultiBody(baseMass=0.0, baseCollisionShapeIndex=edge_collision, basePosition=[1.0, 0.0, 0.43], physicsClientId=self._client)

        body_ids = {
            "cup_001": cup_id,
            "table_001": table_id,
            "hand_001": hand_id,
            "edge_001": edge_id,
        }
        if catch_action:
            catcher_collision = p.createCollisionShape(p.GEOM_BOX, halfExtents=[0.025, 0.18, 0.18], physicsClientId=self._client)
            body_ids["catcher_001"] = p.createMultiBody(
                baseMass=0.0,
                baseCollisionShapeIndex=catcher_collision,
                basePosition=[1.045, 0.0, 0.55],
                physicsClientId=self._client,
            )

        for offset in range(self.background_objects):
            body_ids[f"context_{offset:04d}"] = self._create_background_body(offset, rng)
        return body_ids

    def _create_background_body(self, index: int, rng: random.Random) -> int:
        p = self._p
        shape = p.createCollisionShape(p.GEOM_BOX, halfExtents=[0.025, 0.025, 0.025], physicsClientId=self._client)
        x = rng.uniform(-0.6, 1.6)
        y = rng.choice([-1.0, 1.0]) * rng.uniform(0.55, 1.4)
        return p.createMultiBody(baseMass=0.0, baseCollisionShapeIndex=shape, basePosition=[x, y, 0.05], physicsClientId=self._client)

    def _read_body_states(self, body_ids: dict[str, int]) -> dict[str, dict[str, Any]]:
        states: dict[str, dict[str, Any]] = {}
        for object_id, body_id in body_ids.items():
            position, orientation = self._p.getBasePositionAndOrientation(body_id, physicsClientId=self._client)
            velocity, angular_velocity = self._p.getBaseVelocity(body_id, physicsClientId=self._client)
            states[object_id] = {
                "position": [float(value) for value in position],
                "orientation": [float(value) for value in orientation],
                "velocity": [float(value) for value in velocity],
                "angular_velocity": [float(value) for value in angular_velocity],
            }
        return states


def collate_pybullet_cup_samples(
    samples: list[PyBulletCupSample],
) -> tuple[StateGraphBatch, torch.Tensor, torch.Tensor, torch.Tensor]:
    batch = StateGraphBatch.from_world_states([sample.state for sample in samples], [sample.event for sample in samples])
    return _collate_targets(samples, batch)


def collate_indexed_pybullet_cup_samples(
    samples: list[PyBulletCupSample],
    *,
    max_nodes: int = 16,
    max_depth: int = 1,
) -> tuple[StateGraphBatch, torch.Tensor, torch.Tensor, torch.Tensor]:
    projected_states: list[WorldState] = []
    projected_targets: list[torch.Tensor] = []
    for sample in samples:
        original_ids = list(sample.state.objects)
        selected_ids = _indexed_object_ids(sample.state, sample.event, max_nodes=max_nodes, max_depth=max_depth)
        projected_states.append(_project_state(sample.state, selected_ids))
        original_index = {object_id: index for index, object_id in enumerate(original_ids)}
        selected_target = torch.zeros((len(selected_ids), OBJECT_FEATURE_DIM), dtype=torch.float32)
        for selected_index, object_id in enumerate(selected_ids):
            source_index = original_index.get(object_id)
            if source_index is not None:
                selected_target[selected_index] = sample.target_object_delta[source_index]
        projected_targets.append(selected_target)
    batch = StateGraphBatch.from_world_states(projected_states, [sample.event for sample in samples])
    return _collate_targets(samples, batch, projected_targets=projected_targets)


def _collate_targets(
    samples: list[PyBulletCupSample],
    batch: StateGraphBatch,
    *,
    projected_targets: list[torch.Tensor] | None = None,
) -> tuple[StateGraphBatch, torch.Tensor, torch.Tensor, torch.Tensor]:
    max_objects = batch.object_features.size(1)
    targets = torch.zeros((len(samples), max_objects, OBJECT_FEATURE_DIM), dtype=torch.float32)
    labels = torch.tensor([sample.branch_label for sample in samples], dtype=torch.long)
    causal_k = torch.tensor([sample.causal_working_set_size for sample in samples], dtype=torch.long)
    source_targets = projected_targets or [sample.target_object_delta for sample in samples]
    for index, target in enumerate(source_targets):
        targets[index, : target.size(0)] = target
    return batch, targets, labels, causal_k


def _world_state_from_simulation(
    initial: dict[str, dict[str, Any]],
    *,
    cup_x: float,
    hand_x: float,
    force: float,
    catch_action: bool,
    background_objects: int,
) -> WorldState:
    state = WorldState(time=0.0, metadata={"scenario": "pybullet_cup", "simulator": "pybullet"})
    object_types = {
        "cup_001": "cup",
        "table_001": "table",
        "hand_001": "robot_hand",
        "edge_001": "table_edge",
        "catcher_001": "catcher_hand",
    }
    for object_id, sim_state in initial.items():
        obj_type = object_types.get(object_id, "background_object")
        attributes = {
            "position": sim_state["position"],
            "velocity": sim_state["velocity"],
            "orientation": sim_state["orientation"],
            "angular_velocity": sim_state["angular_velocity"],
            "simulator": "pybullet",
        }
        if object_id == "cup_001":
            attributes["edge_distance"] = max(0.0, 1.0 - cup_x)
        if object_id == "hand_001":
            attributes["hand_distance"] = abs(hand_x - cup_x)
        state.add_object(WorldObject(id=object_id, type=obj_type, attributes=attributes, confidence=0.99))

    cup_edge_strength = 1.0 / (1.0 + max(0.0, 1.0 - cup_x) * 10.0)
    hand_strength = 1.0 / (1.0 + abs(hand_x - cup_x) * 5.0)
    state.add_relation(Relation("cup_001", "table_001", "on_top_of", strength=0.95, confidence=0.98))
    state.add_relation(Relation("hand_001", "cup_001", "impulse_source", strength=min(1.0, force / 1.8), confidence=0.97))
    state.add_relation(Relation("cup_001", "edge_001", "near_edge", strength=cup_edge_strength, confidence=0.96))
    state.add_relation(Relation("hand_001", "cup_001", "near", strength=hand_strength, confidence=0.93))
    if catch_action and "catcher_001" in state.objects:
        state.add_relation(Relation("catcher_001", "cup_001", "catch_region", strength=0.88, confidence=0.93))
    for index in range(background_objects):
        object_id = f"context_{index:04d}"
        if object_id in state.objects:
            state.add_relation(Relation(object_id, "table_001", "scene_context", strength=0.1, confidence=0.7))
    return state


def _target_delta_tensor(
    state: WorldState,
    initial: dict[str, dict[str, Any]],
    final: dict[str, dict[str, Any]],
) -> torch.Tensor:
    target = torch.zeros((len(state.objects), OBJECT_FEATURE_DIM), dtype=torch.float32)
    for index, object_id in enumerate(state.objects):
        before = initial[object_id]
        after = final[object_id]
        position_delta = [after["position"][axis] - before["position"][axis] for axis in range(3)]
        velocity_delta = [after["velocity"][axis] - before["velocity"][axis] for axis in range(3)]
        target[index, 1:4] = torch.tensor(position_delta, dtype=torch.float32)
        target[index, 4:7] = torch.tensor(velocity_delta, dtype=torch.float32)
    return target


def _branch_label(cup_state: dict[str, Any], *, initial_x: float, catch_action: bool, edge_x: float) -> int:
    position = cup_state["position"]
    orientation = cup_state["orientation"]
    roll, pitch, _ = _quat_to_euler(orientation)
    tipped = abs(roll) > 0.8 or abs(pitch) > 0.8
    off_table = position[2] < 0.33 or position[0] > edge_x + 0.12
    if off_table or tipped:
        return 1
    if catch_action and position[0] - initial_x > 0.05:
        return 2
    return 0


def _quat_to_euler(quat: list[float]) -> tuple[float, float, float]:
    x, y, z, w = quat
    sinr_cosp = 2 * (w * x + y * z)
    cosr_cosp = 1 - 2 * (x * x + y * y)
    roll = math.atan2(sinr_cosp, cosr_cosp)
    sinp = 2 * (w * y - z * x)
    pitch = math.copysign(math.pi / 2, sinp) if abs(sinp) >= 1 else math.asin(sinp)
    siny_cosp = 2 * (w * z + x * y)
    cosy_cosp = 1 - 2 * (y * y + z * z)
    yaw = math.atan2(siny_cosp, cosy_cosp)
    return roll, pitch, yaw


__all__ = [
    "PyBulletCupDataset",
    "PyBulletCupSample",
    "collate_indexed_pybullet_cup_samples",
    "collate_pybullet_cup_samples",
]
